# Generated by Django 2.1.2 on 2018-11-09 19:38

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to=accounts.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Projeto', max_length=200)),
                ('projeto', models.CharField(default='Projeto', max_length=200)),
                ('data', models.CharField(default='2018', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='UserUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='guibax', max_length=200)),
                ('docname', models.CharField(blank=True, max_length=30, null=True)),
                ('file', models.FileField(upload_to=accounts.models.user_directory_path)),
            ],
        ),
    ]
