# Generated by Django 2.1.2 on 2018-11-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
