# Generated by Django 2.1.2 on 2018-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181109_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploads',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '.docx'), (2, '.xlsx'), (3, '.ppx')], default=1),
        ),
    ]
