# Generated by Django 2.1.2 on 2018-11-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181115_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojects',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
