# Generated by Django 2.1.2 on 2018-11-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useruploads_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruploads',
            name='user',
        ),
        migrations.AddField(
            model_name='useruploads',
            name='username',
            field=models.CharField(default='Docs', max_length=200),
        ),
        migrations.AlterField(
            model_name='useruploads',
            name='file',
            field=models.FileField(upload_to='<function user_directory_path at 0x7f318abe4d08>/docs'),
        ),
    ]
