# Generated by Django 2.1.2 on 2018-11-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181109_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploads',
            name='file',
            field=models.FileField(upload_to='<function user_directory_path at 0x7f83429b7d08>/docs'),
        ),
    ]
