# Generated by Django 2.1.2 on 2018-11-10 00:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181109_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploads',
            name='file',
            field=models.FileField(upload_to=accounts.models.user_directory_path),
        ),
    ]
