# Generated by Django 2.1.2 on 2018-11-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181109_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploads',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '.docx'), (2, '.xlsx'), (3, '.ppx')], null=True),
        ),
    ]
