# Generated by Django 2.1.2 on 2018-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181109_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('note_text', models.CharField(max_length=1000)),
                ('note_date', models.DateField(verbose_name='Nota')),
            ],
        ),
    ]
