# Generated by Django 2.1.2 on 2018-11-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181112_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdates',
            name='note_date',
            field=models.DateField(),
        ),
    ]
