# Generated by Django 2.1.2 on 2018-10-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mvol', models.IntegerField(default=0)),
                ('cvol', models.IntegerField(default=0)),
                ('porcentage', models.IntegerField(default=0)),
                ('ver_name', models.CharField(default='None', max_length=100)),
                ('ver_date', models.CharField(default='None', max_length=12)),
            ],
        ),
    ]
