# Generated by Django 2.1.2 on 2018-11-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ars', models.IntegerField(default=0)),
                ('ars_p', models.IntegerField(default=0)),
                ('h2', models.IntegerField(default=0)),
                ('h2_p', models.IntegerField(default=0)),
                ('he', models.IntegerField(default=0)),
                ('he_p', models.IntegerField(default=0)),
                ('porcentage', models.IntegerField(default=0)),
                ('ver_name', models.CharField(default='None', max_length=100)),
                ('ver_date', models.CharField(default='None', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
