# Generated by Django 2.1.2 on 2018-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas',
            name='ver_date',
            field=models.DateTimeField(),
        ),
    ]
