# Generated by Django 2.1.2 on 2018-10-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='porcentage',
            field=models.IntegerField(default=0),
        ),
    ]
