# Generated by Django 2.1.2 on 2018-10-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_control', '0002_auto_20181017_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas',
            name='ver_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
