# Generated by Django 2.1.2 on 2018-10-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_control', '0004_auto_20181017_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gas',
            name='mvol',
        ),
    ]
