# Generated by Django 2.1.2 on 2018-10-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_control', '0006_auto_20181025_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='he',
            field=models.IntegerField(default=0),
        ),
    ]
